OPENAI_API_KEY = "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"
REDDIT_CLIENT_ID = "xBzo9mfJuTIWhRvJIQpC_w"
REDDIT_CLIENT_SECRET = "g1RuqPxonhuJ3LsQcsTlMUSRre9fFw"